version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:lts
commands:
  build-app:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Prepare Netlify CLI for deploy
          command: npm i -g netlify-cli
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build static website
          command: yarn build
workflows:
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
jobs:
# Dev job
  build:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - build-app
      - run:
          name: Netlify Deploy
          command: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=public
# Release job
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - build-app
      - run:
          name: Netlify Deploy
          command: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=public
